# Generated by Django 5.0.1 on 2024-01-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_default=models.Value('WAITING'), max_length=20),
        ),
    ]
